spring:
#  profiles:
#    active: dev
  datasource:
    name: serendipity_db
    url: jdbc:mysql://localhost:3306/serendipity_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      # 每次运行该程序，没有表格会新建表格，表内有数据会清空
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    cache: false


#logging:
#  level: debug
